### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ChinaGodMan** [adamlui/github-widescreen#37]
What can this script do on GitHub? I installed it. The sidebar and stuff haven’t changed.

**Comment by adamlui** [comment]
Hey @ChinaGodMan sorry for the late reply

When the script is off, when you edit files it looks like this automatically

![image](https://github.com/user-attachments/assets/7544646b-e795-42a9-baaa-e86c3ca54feb)

But when the script is on, when you click Edit the sidebar auto-hides. Can you confirm this is the case or not for you?
